#!/usr/bin/python3.6
# EASY-INSTALL-ENTRY-SCRIPT: 'asciinema==1.4.0','console_scripts','asciinema'
__requires__ = 'asciinema==1.4.0'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('asciinema==1.4.0', 'console_scripts', 'asciinema')()
    )
